### ISSUE TITLE
Add player flag "PLAYERFLAG_FREEZE"

### ISSUE THREAD

**Issue by CytraL** [def-/ddnet#121]
For that external clients can identify correctly the freeze state is good add a playerFlag for check this...

```CPP
m_InputData.m_PlayerFlags |= PLAYERFLAG_FREEZE;
```

comment if its good or not... for me how modder yes xD

**Comment by def-** [comment]
Instead I would want proper freeze prediction, so that the client can tell freeze tiles and tell when unfreeze will happen, independent of server.
