### ISSUE TITLE
Time slider for envelopes in editor

### ISSUE THREAD

**Issue by def-** [def-/ddnet#122]
03:38 < WolfAlex> just a feature request, what about a time slider for the envelopes in the map editor
03:39 <@deen> I don't understand envelopes and the editor^^
03:40 <@deen> what do you want to do?
03:40 <@deen> you want to move a point left or right (time axis)?
03:42 < WolfAlex> nothig specific.. i thought it would be nice if i, for example have a long animation to skip to specific points to look at the transitions

**Comment by CytraL** [comment]
One feature that few ppl knows is that you can active "ANIM" + "INFO" and you can see and edit envelopes....

![ddnet](https://cloud.githubusercontent.com/assets/731270/5601438/6b835850-92fe-11e4-92ab-f9d91125e5f7.png)
