### ISSUE TITLE
Highlight in Output Console

### ISSUE THREAD

**Issue by MyNewBie** [def-/ddnet#123]
like Highlight in console is that possible ? it would be great

**Comment by def-** [comment]
Yes. I know how to do it in *nix. No idea about Windows but I guess we could find out.

**Comment by MyNewBie** [comment]
so keep issue open maybe someone know how to it for windows

**Comment by def-** [comment]
I think the console is mostly for debugging purposes and doesn't need this. Would also make problems with redirecting it to files.
