### ISSUE TITLE
Tile prediction just on DDRace/DDNet Servers

### ISSUE THREAD

**Issue by tomew** [def-/ddnet#127]
On some maps tiles are mapped from DDNet and they were predicted by DDNet client. It's just annoying.

:+1:

**Comment by def-** [comment]
Why? And what tile prediction?

**Comment by Tomew** [comment]
Example on xPanic. The stop tile, where people stops get predictet but has no effect on the server.

If needed I will show you.

**Comment by def-** [comment]
But on other mods the tiles get used, and they may not be ddrace/ddnet servers. Impossible to reliably tell what the server will do.

**Comment by Tomew** [comment]
Maybe with a clientside filter or the server have to send a special packet so that the client know what to do.

**Comment by def-** [comment]
As a workaround you can use `cl_predict_ddrace 0` on these servers.
