### ISSUE TITLE
boost/variant.hpp: No such file or directory

### ISSUE THREAD

**Issue by TedRoastBeef** [def-/ddnet#132]
[56/71] #1 c++ src/game/server/sql.cpp
In file included from other/mysql/include/mysql_connection.h:30:0,
                 from src/game/server/sql.h:1,
                 from src/game/server/sql.cpp:6:
other/mysql/include/cppconn/connection.h:31:29: fatal error: boost/variant.hpp: No such file or directory
 #include <boost/variant.hpp>

**Comment by def-** [comment]
Install boost?

**Comment by TedRoastBeef** [comment]
where doi have to put the files from the archive?

**Comment by def-** [comment]
On Windows? No idea. They just need to be in the include path.

**Comment by TedRoastBeef** [comment]
my problem is i use codeblock and bam and i have no idea where i have to include this
