### ISSUE TITLE
Can't build on Windows (VS)

### ISSUE THREAD

**Issue by SNSnoop** [def-/ddnet#141]
%comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"" x86

D:\Github\ddnet>..\bam\bam release
other/curl/curl.lua:33: attempt to compare number with nil
bam: script error (-t for more detail)

D:\Github\ddnet>..\bam\bam -t
other/curl/curl.lua:33: attempt to compare number with nil
backtrace:
  other/curl/curl.lua(33): Apply method
  bam.lua(329): build global
  bam.lua(595): (null)
bam: script error (-t for more detail)

**Comment by def-** [comment]
Try removing the `config.lua`, then it should work. (bam's fault)

**Comment by SNSnoop** [comment]
Yes, it has helped, thank you.
