### ISSUE TITLE
Improve skins search...

### ISSUE THREAD

**Issue by CytraL** [def-/ddnet#148]
Actually the client invoke "Find" function (of skins component) when receive a "NETOBJTYPE_CLIENTINFO".... this cause a mistake in the performance. 

One player can update the name but not the skin... in this case the client don't need "re-find" the skin.... and NETOBJTYPE_CLIENTINFO are send by server every net-tick :\

Really this need be revised in the vanilla source and server side.... ~~but because this is a mod... this fix are in client side.~~

**Comment by def-** [comment]
I think this has been implemented in https://github.com/def-/ddnet/commit/7c503c319749653a78547bb8ba1208e2b88fa2cc
