### ISSUE TITLE
unnormal screen

### ISSUE THREAD

**Issue by MyNewBie** [def-/ddnet#151]
in some maps I have problem my screen got grey color and cut 

http://upload7.ir/uploads//92e38ed2e52e360ddbaeae9628092c12dcc13f2d.png

in another map : http://upload7.ir/uploads//35ca90ce6192257356fe7ea262d91f653ca298ba.png

but with other client its work ok :?

**Comment by def-** [comment]
Maybe it's the gfx_noclip setting? Otherwise you could try gfx_asyncrender_old 0 and gfx_threaded_old 0.

**Comment by MyNewBie** [comment]
ok I will test it but my problem is in start of map in other place of map I hadn't problem just when I move my mouse for example on strat part of map it will happened and when I move mouse on right of screen its work ok idk why

**Comment by MyNewBie** [comment]
not work I have no idea

**Comment by def-** [comment]
You could try removing the settings_ddnet.cfg, but I have no idea either.

**Comment by MyNewBie** [comment]
I test all way not work .

**Comment by MyNewBie** [comment]
?

**Comment by def-** [comment]
Strange, I don't know. If you find out, let us know.
