### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by MyNewBie** [def-/ddnet#173]
i got 3 client crash today when dummy was connected .
error : delta unpack failed!
http://image.noelshack.com/fichiers/2015/12/1426681907-capsture.jpg

**Comment by MyNewBie** [comment]
hi deen I debug client today. ddnet client got crash from snapshot.cpp :
http://image.noelshack.com/fichiers/2015/15/1428506259-crash.jpg

**Comment by MyNewBie** [comment]
no idea ?

**Comment by def-** [comment]
m_SnapshotCurrent is too high, but why?

**Comment by MyNewBie** [comment]
I don't know I got sometimes this crash , its just happen when dummy is connect.
