### ISSUE TITLE
About DDNet losing focus.

### ISSUE THREAD

**Issue by imcaffrey** [def-/ddnet#176]
I'm not quite good at this.But Im learning:)

I really enjoyed playing DDNet.

Recently my friends and I discovered sth wrong...

------
Here it goes
Because of the Windows Firewall or sth else,the mouse focus lays on the firewall or UAC.
As a result ,the DDNet client fails to get the focus while loading.
And there happens to be two cursor on the screen.

Whatever done can't be used to refocus...

------

Is there anything we can do to help?

**Comment by def-** [comment]
You could try to figure out what causes it and how to fix it. I have no idea.

**Comment by imcaffrey** [comment]
Glad to know.XD
By the way it seems that the Client does not work well with QQpinyin[an input method]

**Comment by def-** [comment]
I guess that's just the Windows firewall getting in the way. Should be resolved after starting the client once. Don't see how we could do anything about this.
