### ISSUE TITLE
Vote passed delay

### ISSUE THREAD

**Issue by BKer** [def-/ddnet#201]
Hi,

I'm not sure on the how and what, but sometimes it would be nice if the map does not change right after a vote passed. This will leave you time to /save your game. I thought maybe something like setting a sv_map_vote_passed_delay?

Although on DDNetwork the vote options tell you not to vote when people are racing, some people will just vote anyway. This isn't a huge problem, but it does become a problem when you are racing with a dummy and two people join and start a vote. You can't /save your game fast enough and you lost your progress. I don't know if such a delay will become annoying though. Just sharing an idea, because keeping it to myself won't solve my (minor) annoyance for sure :)

**Comment by east** [comment]
We had a it in discussion and I personally like the idea to warn people about a passed vote using a ~10 seconds delay. Nevertheless deen mentioned such a delay would annoy too many people.

**Comment by BKer** [comment]
I can understand the annoyance especially when you join an empty server and call a vote. I did some thinking and on a full server the delay would be even worse, because it would probably take a while for the vote to pass and afterwards you would have the delay. Maybe it is an idea to set something like a minimum voting time? Like as soon as a vote starts you've got those 10 seconds to do a /save. However this would allow over 50% to vote yes or no.

**Comment by feca1997** [comment]
I guess it's only annoying when you are looking for a good map and wanna change maps fast.
For this reason I think the delay should be added only when someone has a racetime more than a min or so.

**Comment by def-** [comment]
This wouldn't really help people who are not in a team (most), so I don't like it. Instead we need something to give players who are far a veto right or higher priority in vote.

**Comment by def-** [comment]
Vetoing is implemented now: https://github.com/def-/ddnet/commit/c79b4d3112f5c32e19362a1cef84b71b94cd8744
