### ISSUE TITLE
Overload vector_base != operator

### ISSUE THREAD

**Issue by CytraL** [def-/ddnet#202]
See here: https://github.com/def-/ddnet/blob/DDRace64/src/base/vmath.h#L42
Now here: https://github.com/teeworlds/teeworlds/blob/master/src/base/vmath.h#L44

:B

**Comment by def-** [comment]
What is it needed for?

**Comment by CytraL** [comment]
for precaution... compiler don't shows any error if you use:  vecA != vecB ... one dev can use with unespected results.
