### ISSUE TITLE
Statboard doesn't fit the screen on lower resolutions

### ISSUE THREAD

**Issue by nzyuzin** [def-/ddnet#211]
>details out of screen for me :
>http://image.noelshack.com/fichiers/2015/22/1432895452-screenshot-2015-05-29-13-28-2s6.jpg
>my graphic settings :
>http://image.noelshack.com/fichiers/2015/22/1432895091-screenshot-2015-05-29-13-28-49.jpg

**Comment by def-** [comment]
Can't reproduce, seems to fit for me.

**Comment by nzyuzin** [comment]
I could actually reproduce the issue.

Statboard initially doesn't show weapons stats and it fills these stats only after kills with certain weapons were scored. You need to set resolution to 1024x768 and when all weapon columns are shown bug is indeed reproduced.

My scenario to reproduce the issue was to go to ctf5 server and stick around there for a while until people score enough kills with different weapons.

**Comment by MyNewBie** [comment]
can you remove whitespaces after flag and best spree or Grabs ? : 
http://image.noelshack.com/fichiers/2015/22/1432895452-screenshot-2015-05-29-13-28-2s6.jpg

**Comment by nzyuzin** [comment]
Yeah, it seems like space is wasted after flags.
For grabs and best spree though I myself find it really interesting to check.

Also I agree that there's too much extra space for best spree, maybe it can be renamed to something shorter.

One way to fix (or rather hide the problem) of this issue would be to allow user to configure which columns in statboard to display.

Thanks for your suggestions!

**Comment by MyNewBie** [comment]
1024x768 size for 4:3 screen
http://image.noelshack.com/fichiers/2015/28/1436527825-screenshot-2015-07-10-15-51-16.png
http://image.noelshack.com/fichiers/2015/28/1436527827-screenshot-2015-07-10-15-53-17.png

**Comment by def-** [comment]
Thanks, should be fixed.

**Comment by MyNewBie** [comment]
yep
http://image.noelshack.com/fichiers/2015/28/1436600701-screenshot-2015-07-11-12-06-08.png
http://image.noelshack.com/fichiers/2015/28/1436600701-screenshot-2015-07-11-12-10-46.png
http://image.noelshack.com/fichiers/2015/28/1436600702-screenshot-2015-07-11-12-05-36.png
