### ISSUE TITLE
Problems with demo autorecording (in German)

### ISSUE THREAD

**Issue by def-** [def-/ddnet#213]
> [09:38:50] ChillerDragon: hasdt du was an dem demo autorecord zeugs geändert? der cuttet jetzt so viel und bei meiner mod verändert sich die zeit nicht die bleibt auf 00:00 und der Client speichert ununterbrochen Demos die 00:00 dauern die kann man nicht anschauen und mein autorecords ordner ist so voll -.- wäre schön wenn man die neue Funktion irgendwo deaktiieren könnte

**Comment by nzyuzin** [comment]
If I understand the problem description correctly (used google translate) and it's related to race mods then #212 should fix that.

If it's not about race mods, however, better description of the problem would be required.

**Comment by def-** [comment]
Thanks, looks great! Fixed by #212
