### ISSUE TITLE
Stat board bind + enter chat = stat board stuck

### ISSUE THREAD

**Issue by PathosEthosLogos** [def-/ddnet#219]
Small issue--to reproduce:

1. Hold stat board bind
2. Press chat bind
3. Press chat bind to send message and get out of chat
4. Press stat board bind to fix

**Comment by nzyuzin** [comment]
Thanks for the bug report!

**Comment by def-** [comment]
That's the default behaviour for all binds, isn't it? Same with hook, fire, hook collisions, etc. I don't consider it that bad.

**Comment by nzyuzin** [comment]
The thing to notice is that this behaviour doesn't hold for scoreboard.
