### ISSUE TITLE
Stat board screenshot at the end of the game not working

### ISSUE THREAD

**Issue by PathosEthosLogos** [def-/ddnet#220]
Enable 20 max stat board screenshots and enable stat board screen shot save
Nothing happens, unless I'm looking through the wrong folder

**Comment by nzyuzin** [comment]
Which directory you're checking?

Is it screenshots/auto/stats?
For me it's not empty at all.

**Comment by PathosEthosLogos** [comment]
Oh interesting, there's no stats folder. I created the stats folder and still nothing afterwards.

**Comment by def-** [comment]
Should be auto-created now.
