### ISSUE TITLE
Demo autorecord notification in scoreboard mode

### ISSUE THREAD

**Issue by user578** [def-/ddnet#227]
Is this feature removed?

**Comment by east** [comment]
Demo autorecord was reverted to an older version since the previous updates broke autorecord on ddnet servers. What notificatin are you talking about?

**Comment by user578** [comment]
http://funkyimg.com/i/YxuD.png
It shows on manual recording only atm.

**Comment by east** [comment]
We indeed could at all recorders there (auto,manual,race) but the thing is they also might have different recording times. So the question is what time should we display?

**Comment by user578** [comment]
Probably all? Personally I only use autorecording and it was a good method to check the recording is working and nothing is broken.
