### ISSUE TITLE
Unicode stuff to write vertically

### ISSUE THREAD

**Issue by def-** [def-/ddnet#229]
This should be forbidden in names, chat and server names:

![foo](https://cloud.githubusercontent.com/assets/2335377/8436136/4e979d48-1f56-11e5-955a-597e8d1679e2.png)

**Comment by heinrich5991** [comment]
Can you say which unicode codepoints cause this?

**Comment by def-** [comment]
In my chat log it looks like this:

```
[15-06-30 18:32:45][chat]: k<C0><8A>i<C0><8A>l<C0><8A>l<C0><8A>a: @@@@@@@@@@@@@
@@@<C0><8A>@@@@@@@@@@@@@@@@<C0><8A>@@@@@@@@@@@@@@@@<C0><8A>@@@@@@@@@@@@@@@@
```

Not sure if that helps

**Comment by Soreu** [comment]
http://forum.ddnet.tw/viewtopic.php?f=4&t=2464

**Comment by heinrich5991** [comment]
Fix is not included in a DDNet release yet.
