### ISSUE TITLE
ddos problems

### ISSUE THREAD

**Issue by egon13** [def-/ddnet#234]
Iam trying fixing the ddos, alone it not work always come connection problems and some timeout
... idk how

**Comment by east** [comment]
DDoS Attacks usually overload your whole network link. Unless the attack is on application layer it's not related to ddnet.

**Comment by egon13** [comment]
idk in the server all timeout and have 999 ping 
more idk

**Comment by def-** [comment]
I don't think we can do anything here.

**Comment by egon13** [comment]
yes i think it's dgt stress or other
