### ISSUE TITLE
ERROR: configure your firewall/nat to let through udp on port 8303

### ISSUE THREAD

**Issue by imcaffrey** [def-/ddnet#245]
while trying to build a server on my own,the client told me that 

>*　ERROR: configure your firewall/nat to let through udp on port 8303

Actually I've already turned off the firewall.So what might be the problem?

I've read the bbs, but there isn't much info.

**Comment by Laxa** [comment]
What is your OS ?
What is bbs ?

**Comment by nzyuzin** [comment]
Are you behind a router or something?

Also you could try changing server port in configuration file in case if the default port (8303) is busy.

**Comment by def-** [comment]
Forward port 8303 UDP to your computer on your router.

**Comment by imcaffrey** [comment]
@Laxa @nzyuzin @def- 
Thanks for your help.
I've contacted the ISP of my district and they admitted there was a mistake.
Thanks again.
and plz close this issue,as it has nothing to do with DDNet
