### ISSUE TITLE
updater should use storage system

### ISSUE THREAD

**Issue by def-** [def-/ddnet#97]
16:14 < CookieMichal> I am on linux and I have created link to ddnet 
                      executable. Like 10s ago I have started ddnet client 
                      using that shortcut and it has updated but in wrong place
16:14 < CookieMichal> please make it update, where the executable is
16:15 <@EastByte> hm you should switch into the directory before starting the 
                  binary
16:15 < CookieMichal> also ddnet.upd appears on my desktop (where the shortcut 
                      is) instead of in that folder (containing executables 
                      and stuff)
16:16 <@EastByte> you are right, this should be fixed

**Comment by Learath2** [comment]
#124 fixes it.
